name: habapp

services:
  gateway:
    build: .
    container_name: hab-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./routes.json:/app/routes.json
    networks:
      - iitg_network
    restart: unless-stopped

networks:
  iitg_network:
    name: iitg_network
    driver: bridge
