const Leave = require("./leaveModel.js");
const multer = require("multer");
const path = require("path");
const fs = require("fs");
const mongoose = require("mongoose");
const { User } = require("../user/userModel.js");

const uploadDir = path.join(__dirname, ".", "uploads");

if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

// const storage = multer.diskStorage({
//   destination: (req, file, cb) => {
//     cb(null, uploadDir);
//   },
//   filename: (req, file, cb) => {
//     const timeStamp = Date.now();
//     cb(null, `leave-${req.user?req.user._id:req.hostel._id}-${timeStamp}-${file.originalname}`);
//   },
// });

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB limit
  fileFilter: (req, file, cb) => {
    const allowedTypes = /jpeg|jpg|png|pdf/;
    const extname = allowedTypes.test(
      path.extname(file.originalname).toLowerCase(),
    );
    const mimetype = allowedTypes.test(file.mimetype);

    if (mimetype && extname) {
      return cb(null, true);
    } else {
      cb(new Error("UNSUPPORTED_FILE_TYPE"));
    }
  },
});

const uploadMiddleware = async (req, res, next) => {
  //console.log("Started uploading document to server");
  upload.single("proofDocument")(req, res, (err) => {
    if (err) {
      if (err.message == "UNSUPPORTED_FILE_TYPE") {
        res.status(400).json({
          message: "Invalid file Type. Only jpg, pdf, png are allowed!",
          error: err.message,
        });
        return;
      }
    }
    //console.log("Passing file to Onedrive Uploader System");
    next();
  });
};

// Get all approved leaves for a specific month/year
async function getRebateDaysForMonth(messHostelId, month, year) {
  const startOfMonth = new Date(year, month - 1, 1);
  const endOfMonth = new Date(year, month, 0, 23, 59, 59);
  let query = {};


  //Find approved leaves in leaves database
  const leaves = await Leave.find({
    messHostel: messHostelId,
    status: "approved",
    isEligibleForRebate: true,
    $or: [{ startDate: { $lte: endOfMonth }, endDate: { $gte: startOfMonth } }],
  }).populate("user", "name rollNumber -_id").lean();

  query.totalRebateDays = leaves.reduce(
    (sum, leave) => sum + leave.eligibleDays,
    0,
  );
  query.eligibleApplications = leaves;

  return query;
}


//Validation of presence of all fields before uploading file to onedrive
const validateApply = async (req, res, next) => {
    const fields = [
      "leaveType",
      "startDate",
      "endDate",
      "bankAccountNumber",
      "bankIFSCCode",
      "bankName",
      "bankAccountHoldersName",
    ]

    const missingFields = fields.filter(field => !req.body[field]);

    if(missingFields.length>0) {
      return res.status(400).json({
        message: "Fields cannot be empty",
        emptyFields: missingFields,
      })
    }

    //console.log(req.body)

    next();
};


//Apply for leave(Student endpoint)
const applyForLeave = async (req, res) => {
  try {
    const {
      leaveType,
      startDate,
      endDate,
      bankAccountNumber,
      bankIFSCCode,
      bankName,
      bankAccountHoldersName,
    } = req.body;
    //No error handling required due to presence of validateApply()

    //File handling
    if (!req.file) {
      res.status(400).json({
        message: "Please upload proof document",
      });
      return;
    }

    //Obtain url and fileName generated by uploadToOnedrive.js
    const proofDocumentUrl = req.file.leaveUrl;
    const proofDocumentFilename = req.file.originalname;

    //Genration of Date object
    const [startYear, startMonth, startDay] = startDate.split("-").map(Number);
    const [endYear, endMonth, endDay] = endDate.split("-").map(Number);
    const start = new Date(startYear, startMonth - 1, startDay);
    const end = new Date(endYear, endMonth - 1, endDay);

    //Get difference between two dates
    const diffBtwDates = Math.abs(end - start);
    const numberOfDays = Math.floor(diffBtwDates / (1000 * 60 * 60 * 24));

    //numberofdays business logic

    if (numberOfDays < 5) {
      res.status(400).json({
        message: "Number of days must be greater than 5",
      });
      return;
    }

    let eligibleDays = 0;
    //Calculation of eligible days
    if (numberOfDays >= 5) {
      eligibleDays = numberOfDays;
    }

    //Validation Rules / Business logic
    if (!(leaveType == "Academic" || leaveType == "Medical")) {
      res.status(400).json({
        message: "Leave type is invalid",
      });
      return;
    }

    if (end - start < 0) {
      res.status(400).json({
        message: "Start, end date combination is invalid",
      });
      return;
    }

    //Autogenerated variables
    const appliedAt = new Date(Date.now());

    //Only if user exists
    if (req.user && req.user.curr_subscribed_mess) {
      const leaveApplication = new Leave({
        user: req.user,
        leaveType,
        startDate: start,
        endDate: end,
        numberOfDays,
        eligibleDays,
        status: "pending",
        proofDocumentUrl,
        proofDocumentFilename,
        appliedAt,
        messHostel: req.user.curr_subscribed_mess,
        bankAccountNumber,
        bankIFSCCode,
        bankName,
        bankAccountHoldersName,
      });

      await leaveApplication.save();

      res.status(201).json({
        message: "Leave Application submited successfully",
        leaveApplication: {
          id: leaveApplication._id,
          user: req.user,
          eligibleDays,
          status: leaveApplication.status,
          appliedAt: leaveApplication.appliedAt,
        },
      });
    } else {
      if (req.user && !req.user.curr_subscribed_mess) {
        res.status(400).json({
          message: "Hostel not provided",
        });
      }
      res.status(400).json({
        message: "Please login first",
      });
    }
  } catch (err) {
    console.error("Error submitting leave application");
    res.status(500).json({
      message: "Error submitting leave application",
      error: err.message,
    });
  }
};

const getApplications = async (req, res) => {
  //Search by User ObjectID
  const myApplications = await Leave.find({
    user: req.user,
  }).sort({
    appliedAt: -1,
  }).lean();

  //For empty applications array
  if (myApplications.length === 0) {
    res.status(200).json({
      message: "No past applications available",
    });
    return;
  }

  res.status(200).json({
    message: "Retrieved applications successfully",
    myApplications,
  });
  return;
};

const getApplicationByID = async (req, res) => {
  const { id } = req.params;
  //Search by Application ObjectID
  if (!mongoose.Types.ObjectId.isValid(id)) {
    res.status(400).json({
      message: "Incorrect Object ID format",
    });
    return;
  } else {
    try {
      let application = await Leave.findById(id).lean();

      if (!application.user.equals(req.user._id)) {
        application = null;
      }

      //For empty appplication variable
      if (application == null) {
        res.status(404).json({
          message: "There are no such leave applications",
        });
      } else {
        res.status(200).json({
          message: "Application retrieved successfully",
          application,
        });
      }
    } catch (err) {
      res.status(500).json({
        message: "Invalid request",
        error: err.message,
      });
    }
  }
};

const getApplicationProof = async (req, res) => {
  const { id } = req.params;
  //Retrieval of proofDocumentUrl from application ObjectID
  if (!mongoose.Types.ObjectId.isValid(id)) {
    res.status(400).json({
      message: "Incorrect Object ID format",
    });
    return;
  } else {
    try {
      const application = await Leave.findOne({
        _id: id,
        user: req.user,
      }).lean();
      if (application == null) {
        res.status(404).json({
          message: "There are no such leave applications",
        });
      } else {
        res.status(200).json({
          message: "Information retrieved successfully",
          proofDocumentUrl: application.proofDocumentUrl,
        });
      }
    } catch (err) {
      res.status(500).json({
        message: "Invalid request",
        error: err.message,
      });
    }
  }
};

const getAllPendingApplications = async (req, res) => {
  const pendingApplications = await Leave.find({
    messHostel: req.hostel,
    status: "pending",
  })
    .sort({
      appliedAt: -1,
    })
    .populate("user", "name rollNumber email -_id");

  //For empty applications array
  if (pendingApplications.length === 0) {
    res.status(404).json({
      message: "No applications available",
    });
    return;
  }

  res.status(200).json({
    message: "Retrieved applications successfully",
    pendingApplications,
  });
  return;
};

const filterApplications = async (req, res) => {
  const query = {
    messHostel: req.hostel,
  };

  if (req.query.status) {
    query.status = req.query.status;
  }

  
  if (req.query.month && req.query.year) {
    let month = parseInt(req.query.month);
    let year = parseInt(req.query.year);
    if(!(month>0 && month <=12)) {
      return res.status(400).json({
        message: "Wrong month format",
      })
    }
    query.startDate = {
      $gte: new Date(year, month - 1, 1),
      $lt: new Date(year, month, 1),
    };
  } else if (req.query.year && !req.query.month) {
      query.startDate = {
        $gte: new Date(req.query.year, 0, 1),
        $lt: new Date(req.query.year + 1, 0, 1),
      };
    }
    else if (req.query.month && !req.query.year) {
    res.status(404).json({
      message: "Please input both year and month",
    });
    return;
    }

  try {
    const filteredApplications = await Leave.find(query).sort({
      appliedAt: -1,
    });

    if (filteredApplications.length === 0) {
      res.status(404).json({
        message: "No such applications could be found",
      });
      return;
    }

    res.status(200).json({
      message: "Documents fetched successfully",
      filteredApplications,
    });
  } catch (err) {
    res.status(500).json({
      message: "Error occured while retrieving leave applications",
      error: err.message,
    });
  }
};

const approveApplication = async (req, res) => {
  const { id } = req.params;

  try {
    let application = await Leave.findById(id);
    if (!application.messHostel.equals(req.hostel._id)) {
      application = null;
    }

    if (application !== null) {
      const query = { status: "approved" };
      if (req.body.feedback) {
        query.feedback = req.body.feedback;
      }

      if (application.eligibleDays >= 5) {
        console.log("Marking eligible for rebate = true");
        query.isEligibleForRebate = true;
      }

      const updatedDoc = await Leave.findByIdAndUpdate(id, query, {new: true}).populate("user", "name rollNumber email -_id");

      res.status(201).json({
        message: `Approved application with ID ${id}`,
        updatedApplication: updatedDoc,
      });
    } else {
      res.status(401).json({
        message: "You are not authorised to do that",
      });
    }
  } catch (err) {
    res.status(500).json({
      message: "Error in approving the leave application",
      error: err.message,
    });
  }
};

const rejectApplication = async (req, res) => {
  const { id } = req.params;

  try {
    let application = await Leave.findById(id);
    if (!application.messHostel.equals(req.hostel._id)) {
      application = null;
    }

    if (application !== null) {
      const query = { status: "rejected" };
      if (req.body.feedback) {
        query.feedback = req.body.feedback;
      }

      const updatedDoc = await Leave.findByIdAndUpdate(id, query, {new: true}).populate("user", "name rollNumber email -_id");

      if (updatedDoc.startDate() <= new Date() && new Date() <= updatedDoc.endDate()) {
        const updatedUser = await User.findByIdAndUpdate(updatedDoc.user, { scannerPermission: true });
        console.log(updatedUser);
      }


      res.status(201).json({
        message: `Rejected application with ID ${id}`,
        updatedApplication: updatedDoc,
      });
    } else {
      res.status(401).json({
        message: "You are not authorised to do that",
      });
    }
  } catch (err) {
    res.status(500).json({
      message: "Error in approving the leave application",
      error: err.message,
    });
  }
};

const getRebateSummary = async (req, res) => {
  const hostel = req.hostel._id;

  if (!(req.query.month && req.query.year)) {
    return res.status(400).json({
      message: "Year or month not specified",
    });
  }

  let year = parseInt(req.query.year);
  let month = parseInt(req.query.month);

  if(!(month>0 && month<=12)) {
    return res.status(400).json({
      message: "Invalid month format"
    })
  }

  console.log(`month = ${month} and year = ${year}`);

  const result = await getRebateDaysForMonth(hostel, month, year);

  res.status(200).json({
    message: "Rebate summary retrieved successfully",
    rebateSummary: result,
  });
};

module.exports = {
  uploadMiddleware,
  applyForLeave,
  getApplications,
  getApplicationByID,
  getApplicationProof,
  getAllPendingApplications,
  filterApplications,
  approveApplication,
  rejectApplication,
  getRebateSummary,
  validateApply
};
