const Leave = require('./leaveModel.js')
const multer = require('multer');
const path = require('path');
const fs = require("fs");
const { default: mongoose } = require('mongoose');


const uploadDir = path.join(__dirname, '.', 'uploads')

if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    const timeStamp = Date.now();
    cb(null, `leave-${req.user._id}-${timeStamp}-${file.originalname}`);
  },
});


const upload = multer({
  storage: storage,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB limit
  fileFilter: (req, file, cb) => {
    const allowedTypes = /jpeg|jpg|png|pdf/;
    const extname = allowedTypes.test(
      path.extname(file.originalname).toLowerCase()
    );
    const mimetype = allowedTypes.test(file.mimetype);

    if (mimetype && extname) {
      return cb(null, true);
    } else {
      cb(new Error("UNSUPPORTED_FILE_TYPE"));
    }
  },
});

const uploadSingle = upload.single('proofDocument');

const uploadMiddleware = async (req, res, next) => {
    uploadSingle(req, res, (err) => {
        if(err) {
            if(err.message == "UNSUPPORTED_FILE_TYPE") {
                res.status(404).json({
                    message: "Invalid file Type. Only jpg, pdf, png are allowed!",
                    error: err.message
                })
            }
        }

        next();
    })
}

const applyForLeave = async (req, res) => {
    try {
        const { leaveType, startDate, endDate } = req.body;
        
        //File handling
        if(!req.file) {
            res.status(400).json({
                message: "Please upload proof document",
            });
            return;
        }
        const proofDocumentUrl = `/api/leave/files/${req.file.filename}`;
        const proofDocumentFilename = req.file.originalname;
        

        //Genration of Date object
        const [startYear, startMonth, startDay] = startDate.split('-').map(Number);
        const [endYear, endMonth, endDay] = endDate.split('-').map(Number);
        const start = new Date(startYear, startMonth-1, startDay)
        const end = new Date(endYear, endMonth-1, endDay)

        //Get difference between two dates
        const diffBtwDates = Math.abs(end-start)

        const numberOfDays = Math.floor(diffBtwDates/(1000*60*60*24));

        //numberofdays business logic

        if(numberOfDays<5) {
            res.status(400).json({
                message: "Number of days must be greater than 5",
            });
            return;
        }

        let eligibleDays = 0;
        //Calculation of eligible days
        if(numberOfDays>=5) {
            eligibleDays = numberOfDays;
        }

        //Validation Rules / Business logic
        if (!(leaveType=="Academic" || leaveType=="Medical")) {
            res.status(400).json({
                message: "Leave type is invalid",
            });
            return;
        }

        if(end-start<0) {
            res.status(400).json({
                message: "Start, end date combination is invalid",
            });
            return;
        }

        //Autogenerated variables        
        const appliedAt = new Date(Date.now());

        //Only if user exists
        if(req.user && req.user.hostel) {
            const leaveApplication = new Leave({
                user: req.user,
                leaveType,
                startDate: start,
                endDate: end,
                numberOfDays,
                eligibleDays,
                status: "pending",
                proofDocumentUrl,
                proofDocumentFilename,
                appliedAt,
                messHostel: req.user.curr_subscribed_mess,
            })

            await leaveApplication.save();

            res.status(201).json({
                message: "Leave Application submited successfully",
                leaveApplication: {
                    id: leaveApplication._id,
                    user: req.user,
                    eligibleDays,
                    status: leaveApplication.status,
                    appliedAt: leaveApplication.appliedAt
                }
            })

        } else {
            if(req.user && !req.user.curr_subscribed_mess) {
                res.status(400).json({
                    message: "Hostel not provided",
                })
            }
            res.status(400).json({
                message: "Please login first",
            })
        }


    }
    catch (err) {
        console.error("Error submitting leave application");
        res.status(500).json({
            message: "Error submitting leave application",
            error: err.message,
        })
    }
}


const getApplications = async (req, res) => {
    //Search by User ObjectID
    const myApplications = await Leave.find({
        user: req.user
    })
    .sort({
        appliedAt: -1
    })

    //For empty applications array
    if (myApplications ==[]) {
        res.status(201).json({
            message: "No past applications available",
        });
        return;
    }

    res.status(201).json({
        message: "Retrieved applications successfully",
        myApplications,
    });
    return;
}


const getApplicationByID = async (req, res) => {
    const { id } = req.params;
    //Search by Application ObjectID
    if(!(mongoose.Types.ObjectId.isValid(id))) {
        res.status(401).json({
            message: "Incorrect Object ID format"
        });
        return;
    }
    else {
        try {
            const application = await Leave.findOne({
                _id: id,
                user: req.user
            });

            //For empty appplication variable
            if(application==null) {
                res.status(404).json({
                    message: "There are no such leave applications"
                })
            }
            else {
                res.status(201).json({
                    message:"Application retrieved successfully",
                    application,
                })
            }
        }
        catch(err) {
            res.status(400).json({
                message: "Invalid request",
                error: err.message
            })
        }
    }

}

const getApplicationProof = async (req, res) => {
    const { id } = req.params;
    //Retrieval of proofDocumentUrl from application ObjectID
    if(!mongoose.Types.ObjectId.isValid(id)) {
        res.status(401).json({
            message: "Incorrect Object ID format"
        });
        return;
    }
    else {
        try {
            const application = await Leave.findOne({
                _id: id,
                user: req.user
            });
            if(application==null) {
                res.status(404).json({
                    message: "There are no such leave applications"
                })
            }
            else {
                res.status(201).json({
                    message:"Information retrieved successfully",
                    proofDocumentUrl: application.proofDocumentUrl,
                })
            }
        }
        catch(err) {
            res.status(400).json({
                message: "Invalid request",
                error: err.message
            })
        } 
    }
}

module.exports = {
    uploadMiddleware,
    applyForLeave,
    getApplications,
    getApplicationByID,
    getApplicationProof
}