const studentApplications = [
    {
      fullname: "Alice Johnson",
      rollno: "240123456",
      from: "Emerald Hostel",
      to: "Sapphire Hostel",
      status: "accepted",
    },
    {
      fullname: "Bob Williams",
      rollno: "240987654",
      from: "Ruby Hall",
      to: "Diamond Hall",
      status: "pending",
    },
    {
      fullname: "Charlie Brown",
      rollno: "240555111",
      from: "Opal Residence",
      to: "Pearl Residence",
      status: "rejected",
    },
    {
      fullname: "Diana Miller",
      rollno: "240333999",
      from: "Topaz Tower",
      to: "Jade Tower",
      status: "accepted",
    },
    {
      fullname: "Ethan Davis",
      rollno: "240777222",
      from: "Garnet Gardens",
      to: "Amethyst Apt",
      status: "pending",
    },
    {
      fullname: "Fiona Clark",
      rollno: "240111222",
      from: "Pearl Residence",
      to: "Emerald Hostel",
      status: "accepted",
    },
    {
      fullname: "George Wilson",
      rollno: "240999888",
      from: "Jade Tower",
      to: "Ruby Hall",
      status: "rejected",
    },
    {
      fullname: "Hannah Green",
      rollno: "240444555",
      from: "Diamond Hall",
      to: "Opal Residence",
      status: "pending",
    },
    {
      fullname: "Ian Turner",
      rollno: "240666777",
      from: "Amethyst Apt",
      to: "Topaz Tower",
      status: "accepted",
    },
    {
      fullname: "Jessica Hill",
      rollno: "240222333",
      from: "Sapphire Hostel",
      to: "Garnet Gardens",
      status: "rejected",
    },
    {
      fullname: "Kevin White",
      rollno: "240888999",
      from: "Emerald Hostel",
      to: "Ruby Hall",
      status: "pending",
    },
    {
      fullname: "Laura King",
      rollno: "240123789",
      from: "Pearl Residence",
      to: "Opal Residence",
      status: "accepted",
    },
    {
      fullname: "Mark Lee",
      rollno: "240987123",
      from: "Diamond Hall",
      to: "Jade Tower",
      status: "rejected",
    },
    {
      fullname: "Nancy Scott",
      rollno: "240555666",
      from: "Topaz Tower",
      to: "Garnet Gardens",
      status: "pending",
    },
    {
      fullname: "Oliver Adams",
      rollno: "240333444",
      from: "Ruby Hall",
      to: "Sapphire Hostel",
      status: "accepted",
    },
    {
      fullname: "Patricia Harris",
      rollno: "240777888",
      from: "Jade Tower",
      to: "Emerald Hostel",
      status: "rejected",
    },
    {
      fullname: "Quentin Jones",
      rollno: "240111999",
      from: "Opal Residence",
      to: "Amethyst Apt",
      status: "accepted",
    },
    {
      fullname: "Rachel Taylor",
      rollno: "240999111",
      from: "Garnet Gardens",
      to: "Pearl Residence",
      status: "pending",
    },
    {
      fullname: "Samuel Moore",
      rollno: "240444222",
      from: "Sapphire Hostel",
      to: "Diamond Hall",
      status: "rejected",
    },
    {
      fullname: "Tina Wright",
      rollno: "240666333",
      from: "Amethyst Apt",
      to: "Topaz Tower",
      status: "accepted",
    },
  ];

  export default studentApplications